class ServerConfig:
    WIFI_SSID = ""
    WIFI_PASSWORD = ""
    WIFI_CONNECTION_RETRIES = 5
    WIFI_CONNECTION_DELAY = 5

    HOTSPOT_NAME = "pico_hotspot"
    HOTSPOT_PASSWORD = "pico_hotspot1234"

    SERVER_PORT = 80
    DEBUG_MODE = True

    MAX_CONNECTION_PAYLOAD_LENGTH = 1024
    MAINLOOP_DELAY = 0.1
