class ServerConfig:
    WIFI_SSID = ""
    WIFI_PASSWORD = ""
    WIFI_CONNECTION_RETRIES = 5
    WIFI_CONNECTION_DELAY = 5

    SERVER_PORT = 80

    MAX_CONNECTION_PAYLOAD_LENGTH = 1024
    MAINLOOP_DELAY = 0.1
